CREATE TABLE doctors(
    id SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(20) NOT NULL
);

CREATE TABLE patients(
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(20) NOT NULL
);

CREATE TABLE devices(
	id SERIAL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
    taken BOOLEAN NOT NULL DEFAULT FALSE,
    loinc_num VARCHAR(20) NOT NULL,
    doctor_id INT DEFAULT NULL,
    patient_id INT DEFAULT NULL,
    FOREIGN KEY(doctor_id) REFERENCES doctors(id) ON DELETE SET NULL,
    FOREIGN KEY(patient_id) REFERENCES patients(id) ON DELETE SET NULL
);

CREATE TABLE measurements(
	id SERIAL PRIMARY KEY,
	val DECIMAL NOT NULL,
	loinc_num VARCHAR(20) NOT NULL,
	device_id INT,
	patient_id INT,
    FOREIGN KEY(device_id) REFERENCES devices(id) ON DELETE SET NULL,
    FOREIGN KEY(patient_id) REFERENCES patients(id) ON DELETE SET NULL
);
